matrix:
  platform:
  - win64,windows
  - linux64,linux

branch_patterns:
- master
- fb-.*

git:
  reference: "$WORKSPACE/../../Shared/ref_repos/jobs_done10"

branch-master:cron: |
  H 22 * * *

junit_patterns:
- "**/build/*.xml"

console_color:

platform-windows:build_batch_commands:
- |
  cd "%WORKSPACE%/jobs_done10"
  set CONDA_FORCE_32BIT=
  if "{platform}" == "win32" set CONDA_FORCE_32BIT=1

  call conda clean --lock
  call conda devenv
  if not "%ERRORLEVEL%" == "0" exit /B 1

  call activate _jobs_done10
  if not "%ERRORLEVEL%" == "0" exit /B 1

  pytest --color=yes --junitxml=build/tests.xml --showlocals

platform-linux:build_shell_commands:
- |
  cd $WORKSPACE/jobs_done10
  conda clean --lock
  conda devenv
  source activate jobs_done10
  pytest --color=yes --junitxml=build/tests.xml --showlocals


notify_stash:

display_name: "[{branch}] {name} {platform}"

label_expression: "{platform}"

timeout: 20

timestamps: 
