matrix:
  platform:
  - win32,windows
  - win64,windows
  - linux64,linux

branch_patterns:
- master
- fb-.*

git:
  reference: "$WORKSPACE/../../Shared/ref_repos/jobs_done10"

junit_patterns:
- "**/build/*.xml"

console_color:

platform-windows:build_batch_commands:
- |
  cd "%WORKSPACE%/jobs_done10"
  set CONDA_FORCE_32BIT=
  if "{platform}" == "win32" set CONDA_FORCE_32BIT=1

  call conda clean --lock
  call conda env update -n _jobs_done10-{platform} --prune
  if not "%ERRORLEVEL%" == "0" exit /B 1

  call activate _jobs_done10-{platform}
  if not "%ERRORLEVEL%" == "0" exit /B 1

  py.test --junitxml=build/tests.xml --showlocals

platform-linux:build_shell_commands:
- |
  # run-chroot-command is here temporarily: ETK-1158
  $WORKSPACE/jobs_done10/run-chroot-command bash -c "
      cd $WORKSPACE/jobs_done10
      conda clean --lock
      conda env create --force
      source activate jobs_done10
      py.test --junitxml=build/tests.xml --showlocals
  "


notify_stash:

display_name: "[{branch}] {name} {platform}"

label_expression: "{platform} && !12.0"

timeout: 20

timestamps: 