matrix:
  dist:
  - 12.0

  platform:
  - win32,windows
  - win64,windows
  - redhat64,linux

branch_patterns:
- master
- fb-.*

junit_patterns:
- "**/build/{dist}-{platform}-tests/*.xml"

platform-windows:build_batch_commands:
- "%AA_AASIMAR_AA% -t project.update jobs_done10 --projects-dir=%WORKSPACE% --dependencies-only --sources=head --binaries=none"
- "%AA_AASIMAR_AA% -t project.build jobs_done10 --projects-dir=%WORKSPACE% --dist={dist} --platform={platform}"

platform-linux:build_shell_commands:
- "$AA_AASIMAR_AA -t project.update jobs_done10 --projects-dir=$WORKSPACE --dependencies-only --sources=head --binaries=none"
- "$AA_AASIMAR_AA -t project.build jobs_done10 --projects-dir=$WORKSPACE --dist={dist} --platform={platform}"

description_regex: "HUDSON DESCRIPTION\\: (.*)"

notify_stash:
  url: "https://eden.esss.com.br/stash"
  username: "dev"
  password: "esss0dev"

