matrix:
  dist:
  - 12.0

  platform:
  - win32,windows
  - win64,windows
  - redhat64,linux

branch_patterns:
- master
- fb-.*

git:
  shallow_clone: true
  reference: "$AA_SYSTEM_REF_REPOS/{name}"

additional_repositories:
- git:
    url: "ssh://git@eden.fln.esss.com.br:7999/esss/ben10.git"
    branch: "master"
    shallow_clone: true
    reference: "$AA_SYSTEM_REF_REPOS/ben10"

junit_patterns:
- "**/build/{dist}-{platform}-tests/*.xml"
- "ben10/pytest.xml"

platform-windows:build_batch_commands:
- |
  %AA_AASIMAR_AA_CONFIG% --aasimar-ref=origin/master --dist-ref=origin/master --dist={dist} --platform={platform} --projects-dir=%WORKSPACE% --conf-dir=%WORKSPACE% --reset-env --load-env=git || goto :eof
  %AA_AASIMAR_AA% project.build jobs_done10 || goto :eof

platform-linux:build_shell_commands:
- |
  $AA_AASIMAR_AA_CONFIG --aasimar-ref=origin/master --dist-ref=origin/master --dist={dist} --platform={platform} --projects-dir=$WORKSPACE --conf-dir=$WORKSPACE --reset-env --load-env=git
  $AA_AASIMAR_AA project.build jobs_done10

scm_poll: |
  # build every 2 hours between 2h and 20h
  H 2-20/2 * * *

description_regex: "HUDSON DESCRIPTION\\: (.*)"

notify_stash:

display_name: "[{branch}] {name} {dist}-{platform}"

label_expression: "dist-{dist} && {platform} && team-bos"

timeout: 5
