matrix:
  dist:
  - 12.0
  - conda

  platform:
  - win32,windows
  - win64,windows
  - linux64,linux

dist-12.0:platform-linux:exclude: "yes"

branch_patterns:
- master
- fb-.*

git:
  reference: "$AA_SYSTEM_REF_REPOS/{name}"

additional_repositories:
- git:
    url: "ssh://git@eden.fln.esss.com.br:7999/esss/eden.git"
    branch: "{branch}"
    reference: "$AA_SYSTEM_REF_REPOS/eden"
- git:
    url: "ssh://git@eden.fln.esss.com.br:7999/esss/ben10.git"
    branch: "{branch}"
    reference: "$AA_SYSTEM_REF_REPOS/ben10"
- git:
    url: "ssh://git@eden.fln.esss.com.br:7999/esss/aasimar.git"
    branch: "{branch}"
    reference: "$AA_SYSTEM_REF_REPOS/aasimar"

junit_patterns:
- "**/build/tests/*.xml"
- "ben10/pytest.xml"

platform-windows:build_batch_commands:
- |
  %AA_AASIMAR_AA_CONFIG% --aasimar-ref=origin/master --dist-ref=origin/master --dist={dist} --platform={platform} --projects-dir=%WORKSPACE% --conf-dir=%WORKSPACE% --reset-env --load-env=git || goto :eof
  %AA_AASIMAR_AA% project.build jobs_done10 || goto :eof

dist-conda:platform-linux:build_shell_commands:
- |
  $WORKSPACE/eden/bin/run-chroot-command bash -c "
      source $WORKSPACE/eden/bin/aa_setup_slave
      aa.bash project.build jobs_done10 --
  "


dist-12.0:branch-master:scm_poll: |
  # build at 23pm
  H 23 * * *

dist-conda:platform-linux:branch-master:scm_poll: |
  # build at 23pm
  H 23 * * *

description_regex: "HUDSON DESCRIPTION\\: (.*)"

notify_stash:

display_name: "[{branch}] {name} {platform} {dist}"

label_expression: "{dist} && {platform}"

timeout: 20
