matrix:
  platform:
  - win64,windows
  - linux64,linux

branch_patterns:
- master
- fb-.*

git:
  reference: "$WORKSPACE/../../Shared/ref_repos/jobs_done10"

branch-master:cron: |
  H 22 * * *

junit_patterns:
- "**/build/*.xml"

console_color:

platform-windows:build_batch_commands:
- |
  cd "%WORKSPACE%/jobs_done10"

  for /F %%i in ('conda info --root') do set CONDA_ROOT=%%i
  "%CONDA_ROOT%\python" -m virtualenv .env
  if errorlevel 1 exit /B 1

  call .env\Scripts\activate
  if errorlevel 1 exit /B 1

  pip install -e .[testing]
  if errorlevel 1 exit /B 1

  pytest --color=yes --junitxml=build/tests.xml --showlocals

platform-linux:build_shell_commands:
- |
  cd "$WORKSPACE/jobs_done10"

  $(conda info --root)/bin/python -m virtualenv .env
  source .env/bin/activate
  pip install -e .[testing]

  pytest --color=yes --junitxml=build/tests.xml --showlocals


notify_stash:

display_name: "[{branch}] {name} {platform}"

label_expression: "{platform}"

timeout: 20

timestamps: 
