default_language_version:
    python: python3.10
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: "v0.3.7"
  hooks:
    - id: ruff-format
-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==24.1.1]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        files: ^(src/|tests/)
        args: []
        additional_dependencies: [attrs]
