language: python

jobs:
  include:
    - python: "3.6"
      install:
      - "touch .env"
      - "docker build . -t jobsdone --build-arg SETUPTOOLS_SCM_PRETEND_VERSION=0.1"
      script:
      - "docker run jobsdone pytest src --color=yes"

    - stage: "deploy"
      python: "3.6"
      install: pip install -U setuptools setuptools_scm
      script: skip

      deploy:
        provider: pypi
        user: nicoddemus
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        password:
          secure: CHqibt+lCwLtdszxBDD+3UOSrOs6MuCDtBR5W9zbHkXoeDt+7CmDzfitzztDC+BqfNkyGXrYH8ibyeijtRnPbnJmbePkOci9ClACfWjnwcv0RLevqdJAKsWTfybI5aA00H09Sb5nDGsfsFXoAdTaNXmgWtiiwXXYcAz9tQMjTLDSSZxa5OXoBFx2lxObh+sbNJZsmNKKTgFM2PGVg4eu+6OHe/FgN860KxID4eF/P4pQMqK6VVsPU36G2NVf/6uXT6qcwZujX478r/S/Iy/+c/rpvQqddMIQgCaGJAkQPhRflO4aoUDPTFseKy8qdIBG1aa9kqbF0Ku02qafZmcWbwQ7S/V8rW7ZI9WM/R+1k7LH47m1a2hW4+qr5mzxTXhOGuPfQAtXg5O3cE1miBtQg636IowAE/qL8cVj2Jp33GDdCgdmFknORKgpC1RkSp8BMjitmOHVS/n7qmZjIVOF2V6vF8USJkibVJflZVhNeBPhOWb9znvEN+h23YkRJm15TowJLyJynywrioHaC+L3htrNMQ0818Zvv99IuyWT03tTNx8QsMticCPfscesWiq1LCh7uriZNIotbhiC4DbtVkDSkJHfr+PKZBHn9JA+ni7JhwlgbbemcoF0zOca9sQpmYMZojU79oOP5NfYgWxdwKonyLAOgV9yv9VMlVpJQCY=
        on:
          tags: true
          repo: ESSS/jobs_done10

