name: jobs_done10

dependencies:
  - boltons
  - jenkins-webapi
  - mock
  - pytest
  - pyyaml
  {% if os.sys.platform.startswith('linux') %}
  - git
  {% endif %}

environment:
  - PYTHONPATH:
    - {{ os.path.join(root, 'source', 'python') }}
