name: jobs_done10-py36

dependencies:
  - click
  - jenkins-webapi
  - python >=3.6
  - pytest >=3
  - pyyaml
  {% if os.sys.platform.startswith('linux') %}
  - git
  {% endif %}

environment:
  PYTHONPATH:
    - {{ os.path.join(root, 'source', 'python') }}
  PATH:
    - {{ os.path.join(root, 'bin') }}
