#!/bin/bash

if [ -n "$SCHROOT_CHROOT_NAME" ]; then
    echo 'This script should be executed outside a chroot environment.'
    exit 1
fi

if [ -z $CHROOT ]; then
    CHROOT=centos5-64-session
fi

if [ "$CHROOT_VERBOSE" != 0 ]; then
    echo "Using chroot $CHROOT. You can customize it setting CHROOT environment variable."
    echo "Run schroot --list --all to list all available chroots and sessions."
    echo "Prefer to use existing sessions"
    echo ""
fi

xhost +local: > /dev/null
TEMP_FILE=$(mktemp)
chmod a+x $TEMP_FILE

echo "
#/bin/bash

source $HOME/.bashrc
export LANG=en_US.UTF-8
export GNOME_DESKTOP_SESSION_ID=$GNOME_DESKTOP_SESSION_ID
export NODE_NAME=$NODE_NAME
export WORKSPACE=$WORKSPACE
export DISPLAY=$DISPLAY
export JOB_URL=$JOB_URL

\"\$@\"
" >> $TEMP_FILE

# It should be the last command so the return value is right.
schroot -r -c $CHROOT -d $HOME -- bash $TEMP_FILE "$@" && rm $TEMP_FILE
