# vim: set ft=yaml ts=2 sw=2:

name: jobs_done10 CI

on: [push]

jobs:
  test:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          touch .env &&
          docker build . -t jobsdone --build-arg SETUPTOOLS_SCM_PRETEND_VERSION=0.1 &&
          docker run jobsdone pytest src --color=yes

  deploy:
    runs-on: 'ubuntu-latest'

    needs: ['test']

    steps:
      - uses: actions/checkout@v2

      - name: Build package
        run: |
          python -m pip install --upgrade pip setuptools setuptools_scm &&
          python setup.py sdist bdist_wheel
