name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker build . -t jobsdone --build-arg SETUPTOOLS_SCM_PRETEND_VERSION=0.1
          docker run jobsdone pytest tests --color=yes
